name: Angular CI with SonarCloud

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js 22
      uses: actions/setup-node@v3
      with:
        node-version: '22'

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: npm run build -- --prod

    - name: SonarCloud Analysis
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        projectKey: "Mariamfrm_angular"
        organization: "Mariamfrm"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Run tests
      run: npm test -- --watch=false --browsers=ChromeHeadless
